# Generated by Django 4.2.11 on 2026-03-22 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Popis / meno hosťa')),
                ('key_type', models.CharField(choices=[('one_time', 'Jednorazový'), ('timed', 'Časový')], max_length=20, verbose_name='Typ kľúča')),
                ('ldap_username', models.CharField(max_length=64, unique=True, verbose_name='LDAP meno')),
                ('ldap_password', models.CharField(max_length=128, verbose_name='Heslo (plain, zobrazí sa raz)')),
                ('valid_hours', models.PositiveIntegerField(blank=True, help_text='Len pre časový typ. Null = ručne definovaná expirácia.', null=True, verbose_name='Platnosť (hodiny)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiruje')),
                ('used', models.BooleanField(default=False, verbose_name='Použitý')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Čas použitia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorený')),
                ('email_sent_to', models.EmailField(blank=True, max_length=254, verbose_name='Email odoslaný na')),
                ('ldap_deleted', models.BooleanField(default=False, verbose_name='LDAP účet zmazaný')),
            ],
            options={
                'verbose_name': 'Dočasný kľúč',
                'verbose_name_plural': 'Dočasné kľúče',
                'ordering': ['-created_at'],
            },
        ),
    ]
