# Generated by Django 4.2.11 on 2026-03-22 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempkey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL, verbose_name='Vytvoril'),
        ),
    ]
