# Generated by Django 4.2.11 on 2026-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusPostAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password_attempt', models.CharField(blank=True, db_column='pass', max_length=64)),
                ('reply', models.CharField(blank=True, max_length=32)),
                ('called_station_id', models.CharField(blank=True, db_column='calledstationid', max_length=50)),
                ('calling_station_id', models.CharField(blank=True, db_column='callingstationid', max_length=50)),
                ('auth_date', models.DateTimeField(blank=True, db_column='authdate', null=True)),
            ],
            options={
                'verbose_name': 'Auth log',
                'db_table': 'radius_postauth',
                'ordering': ['-auth_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RadiusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_session_id', models.CharField(max_length=64, verbose_name='Session ID')),
                ('acct_unique_id', models.CharField(blank=True, max_length=32, verbose_name='Unique ID')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='Používateľ')),
                ('realm', models.CharField(blank=True, max_length=64)),
                ('nas_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='NAS IP')),
                ('nas_port_id', models.CharField(blank=True, max_length=15, verbose_name='NAS Port')),
                ('nas_port_type', models.CharField(blank=True, max_length=32)),
                ('nas_identifier', models.CharField(blank=True, max_length=64, verbose_name='AP meno')),
                ('acct_start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Začiatok')),
                ('acct_update_time', models.DateTimeField(blank=True, null=True, verbose_name='Posledný update')),
                ('acct_stop_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Koniec')),
                ('acct_session_time', models.IntegerField(blank=True, null=True, verbose_name='Trvanie (s)')),
                ('acct_authentic', models.CharField(blank=True, max_length=32)),
                ('connect_info_start', models.CharField(blank=True, max_length=50, verbose_name='Rýchlosť pri pripojení')),
                ('connect_info_stop', models.CharField(blank=True, max_length=50)),
                ('acct_input_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Stiahnuté (B)')),
                ('acct_output_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Odoslané (B)')),
                ('called_station_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='AP:SSID')),
                ('calling_station_id', models.CharField(blank=True, max_length=50, verbose_name='MAC zariadenia')),
                ('acct_terminate_cause', models.CharField(blank=True, max_length=32, verbose_name='Dôvod ukončenia')),
                ('service_type', models.CharField(blank=True, max_length=32)),
                ('framed_protocol', models.CharField(blank=True, max_length=32)),
                ('framed_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP zariadenia')),
            ],
            options={
                'verbose_name': 'RADIUS session',
                'verbose_name_plural': 'RADIUS sessions',
                'db_table': 'radius_sessions',
                'ordering': ['-acct_start_time'],
                'managed': True,
                'indexes': [models.Index(fields=['username', 'acct_stop_time'], name='radius_sess_usernam_e847bd_idx'), models.Index(fields=['called_station_id'], name='radius_sess_called__0c4245_idx')],
            },
        ),
    ]
