# Generated by Django 4.2.11 on 2026-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('test', 'Test')], default='test', max_length=20)),
                ('alertname', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Push notifikácia',
                'verbose_name_plural': 'Push notifikácie',
                'ordering': ['-created_at'],
            },
        ),
    ]
