# Generated by Django 4.2.11 on 2026-08-16 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
