# Generated by Django 4.2.11 on 2026-08-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_pushsubscription_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
