# Generated by Django 4.2.11 on 2026-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=150, verbose_name='Admin')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Akcia')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='Cieľ')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detaily')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP admina')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Čas')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logy',
                'ordering': ['-timestamp'],
            },
        ),
    ]
