apiVersion: 1

datasources:
  - name: WifiKeeper DB
    uid: wifikeeper-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: $POSTGRES_DB
    user: grafana_ro
    isDefault: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $GRAFANA_PG_PASSWORD
